/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DAO.CompraDAO;
import controlador.DAO.DetalleCompraDAO;
import controlador.DAO.ProductoDAO;
import controlador.DAO.ProveedorDAO;
import controlador.utilidades.Controladores;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;
import modelo.Proveedor;

/**
 *
 * @author USUARIO
 */
public class CompraProveedor extends javax.swing.JFrame {
    
    private CompraDAO cdao = new CompraDAO();
    private ProductoDAO pdao = new ProductoDAO();
    private Producto producto = new Producto();
    private ProveedorDAO proveedor = new ProveedorDAO();
    Controladores controles = new Controladores();
    private DetalleCompraDAO detalleCompra = new DetalleCompraDAO();
    ArrayList<Producto> listaProductos = new ArrayList<Producto>();
    DetalleCompra dc = new DetalleCompra();
    Compra compra = new Compra();
    Date fecha = new Date();
    Double subtotal = 0.0;
    String nombre = "";
    String id = "";
    Producto produc = new Producto();
    Boolean efectivo = false;
    Boolean Tarjeta = false;
    String formaPago = "";

    public CompraProveedor() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtIdProveedor.setVisible(false);
        lblAvisoCompra.setVisible(false);
        lblAvisoCedula.setVisible(false);
        lblAvisoProveedor.setVisible(false);
        lblAvisoCodigo.setVisible(false);
        lblAvisoCantidad.setVisible(false);
        lblAvisoSubtotal.setVisible(false);
        lblAvisoTotal.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSLabelImage4 = new necesario.RSLabelImage();
        btnProveedor = new newscomponents.RSButtonBigIcon_new();
        btnRegistrar = new newscomponents.RSButtonBigIcon_new();
        btnProducto = new newscomponents.RSButtonBigIcon_new();
        btnCompraProveedor = new newscomponents.RSButtonBigIcon_new();
        btnMinimizar = new RSMaterialComponent.RSButtonIconDos();
        btnSalir = new RSMaterialComponent.RSButtonIconDos();
        rSLabelImage2 = new necesario.RSLabelImage();
        rSLabelHora1 = new rojeru_san.rsdate.RSLabelHora();
        jLabel23 = new javax.swing.JLabel();
        btnRegresar = new RSMaterialComponent.RSButtonCustomIcon();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rSLabelImage1 = new rojeru_san.rslabel.RSLabelImage();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bntCalcularIva = new rojerusan.RSButtonHover();
        btnBuscarCodProductoCP = new rojerusan.RSButtonHover();
        txtCedulaCP = new javax.swing.JTextField();
        txtProveedorCP = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        lblProveedor = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        labelIcon5 = new necesario.LabelIcon();
        btnGuardarCP = new rojerusan.RSButtonHover();
        jlblSubtotal = new javax.swing.JLabel();
        jlblIva = new javax.swing.JLabel();
        jlblTotalPago = new javax.swing.JLabel();
        txtSubtotalCP = new javax.swing.JTextField();
        txtTotalPagarCP = new javax.swing.JTextField();
        labelIcon8 = new necesario.LabelIcon();
        labelIcon9 = new necesario.LabelIcon();
        labelIcon14 = new necesario.LabelIcon();
        labelIcon15 = new necesario.LabelIcon();
        lblNroFactura = new javax.swing.JLabel();
        txtnroCompraCP = new javax.swing.JTextField();
        rSLabelFecha1 = new rojeru_san.rsdate.RSLabelFecha();
        lblFormaPago = new javax.swing.JLabel();
        checkBoxIVACP = new javax.swing.JCheckBox();
        btnBuscarCedulaCP1 = new rojerusan.RSButtonHover();
        txtIdProveedor = new javax.swing.JTextField();
        jlblSubtotal1 = new javax.swing.JLabel();
        txtCodProductoCP = new javax.swing.JTextField();
        btnLimpiar = new rojerusan.RSButtonHover();
        labelIcon1 = new necesario.LabelIcon();
        lblAvisoTotal = new javax.swing.JLabel();
        lblAvisoCompra = new javax.swing.JLabel();
        lblAvisoCedula = new javax.swing.JLabel();
        lblAvisoProveedor = new javax.swing.JLabel();
        lblAvisoCantidad = new javax.swing.JLabel();
        lblAvisoSubtotal = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblAvisoCodigo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProductoCP = new RSMaterialComponent.RSTableMetro();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtDetalleCompra = new RSMaterialComponent.RSTableMetro();
        btnTarjeta = new rojerusan.RSButtonHover();
        btnEfectivo1 = new rojerusan.RSButtonHover();
        rSLabelFecha2 = new rojeru_san.rsdate.RSLabelFecha();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setLayout(null);

        rSLabelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSistemaFinal.jpg"))); // NOI18N
        jPanel2.add(rSLabelImage4);
        rSLabelImage4.setBounds(870, 10, 140, 80);

        btnProveedor.setBackground(new java.awt.Color(0, 153, 102));
        btnProveedor.setText("Proveedor");
        btnProveedor.setBgHover(new java.awt.Color(102, 102, 102));
        btnProveedor.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON);
        btnProveedor.setSizeIcon(50.0F);
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnProveedor);
        btnProveedor.setBounds(280, 10, 140, 80);

        btnRegistrar.setBackground(new java.awt.Color(0, 153, 102));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBgHover(new java.awt.Color(102, 102, 102));
        btnRegistrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON_ADD);
        btnRegistrar.setSizeIcon(50.0F);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar);
        btnRegistrar.setBounds(120, 10, 140, 80);

        btnProducto.setBackground(new java.awt.Color(0, 153, 102));
        btnProducto.setText("Producto");
        btnProducto.setBgHover(new java.awt.Color(102, 102, 102));
        btnProducto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SHOPPING_BASKET);
        btnProducto.setSizeIcon(50.0F);
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });
        jPanel2.add(btnProducto);
        btnProducto.setBounds(580, 10, 140, 80);

        btnCompraProveedor.setBackground(new java.awt.Color(0, 153, 102));
        btnCompraProveedor.setText("Compra ");
        btnCompraProveedor.setBgHover(new java.awt.Color(102, 102, 102));
        btnCompraProveedor.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SHOPPING_CART);
        btnCompraProveedor.setSizeIcon(50.0F);
        btnCompraProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnCompraProveedor);
        btnCompraProveedor.setBounds(430, 10, 140, 80);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 40, 1040, 100);

        btnMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setForeground(new java.awt.Color(102, 102, 102));
        btnMinimizar.setBackgroundHover(new java.awt.Color(0, 102, 204));
        btnMinimizar.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnMinimizar.setForegroundText(new java.awt.Color(102, 102, 102));
        btnMinimizar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REMOVE);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimizar);
        btnMinimizar.setBounds(960, 0, 40, 40);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setForeground(new java.awt.Color(102, 102, 102));
        btnSalir.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnSalir.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnSalir.setForegroundText(new java.awt.Color(102, 102, 102));
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);
        btnSalir.setBounds(1000, 0, 40, 40);

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSistemaFinal.jpg"))); // NOI18N
        jPanel1.add(rSLabelImage2);
        rSLabelImage2.setBounds(0, 0, 50, 40);

        rSLabelHora1.setForeground(new java.awt.Color(102, 102, 102));
        rSLabelHora1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(rSLabelHora1);
        rSLabelHora1.setBounds(730, 10, 200, 20);

        jLabel23.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("ELECTROCASA");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(60, 0, 190, 30);

        btnRegresar.setBackground(new java.awt.Color(0, 204, 51));
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setColorIcon(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REPLAY);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(260, 10, 140, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSistemaFinal.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Telf: 0939258198");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("ELECTROCASA");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("RUC:1198367544001");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("Direccion: Loja, Ecuador");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(239, 239, 239))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(299, 299, 299)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(rSLabelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(rSLabelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(1, 1, 848, 74);

        bntCalcularIva.setBackground(new java.awt.Color(102, 153, 255));
        bntCalcularIva.setText("Calcular");
        bntCalcularIva.setColorHover(new java.awt.Color(102, 102, 102));
        bntCalcularIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularIvaActionPerformed(evt);
            }
        });
        jPanel3.add(bntCalcularIva);
        bntCalcularIva.setBounds(650, 440, 93, 24);

        btnBuscarCodProductoCP.setBackground(new java.awt.Color(204, 0, 255));
        btnBuscarCodProductoCP.setText("Buscar");
        btnBuscarCodProductoCP.setColorHover(new java.awt.Color(102, 102, 102));
        btnBuscarCodProductoCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCodProductoCPActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarCodProductoCP);
        btnBuscarCodProductoCP.setBounds(584, 218, 82, 22);

        txtCedulaCP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCedulaCP.setForeground(new java.awt.Color(102, 102, 102));
        txtCedulaCP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtCedulaCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCedulaCPMouseClicked(evt);
            }
        });
        txtCedulaCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaCPActionPerformed(evt);
            }
        });
        txtCedulaCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaCPKeyTyped(evt);
            }
        });
        jPanel3.add(txtCedulaCP);
        txtCedulaCP.setBounds(310, 120, 180, 18);

        txtProveedorCP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtProveedorCP.setForeground(new java.awt.Color(102, 102, 102));
        txtProveedorCP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtProveedorCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtProveedorCPMouseClicked(evt);
            }
        });
        txtProveedorCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorCPActionPerformed(evt);
            }
        });
        jPanel3.add(txtProveedorCP);
        txtProveedorCP.setBounds(310, 150, 180, 18);

        lblCedula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(102, 102, 102));
        lblCedula.setText("Cédula:");
        jPanel3.add(lblCedula);
        lblCedula.setBounds(190, 120, 80, 30);

        lblProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(102, 102, 102));
        lblProveedor.setText("Proveedor:");
        jPanel3.add(lblProveedor);
        lblProveedor.setBounds(190, 150, 80, 30);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(102, 102, 102));
        lblCodigo.setText("Código:");
        jPanel3.add(lblCodigo);
        lblCodigo.setBounds(190, 190, 80, 20);

        labelIcon5.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        jPanel3.add(labelIcon5);
        labelIcon5.setBounds(250, 500, 30, 30);

        btnGuardarCP.setBackground(new java.awt.Color(0, 204, 51));
        btnGuardarCP.setText("Guardar");
        btnGuardarCP.setColorHover(new java.awt.Color(102, 102, 102));
        btnGuardarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCPActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardarCP);
        btnGuardarCP.setBounds(290, 500, 130, 30);

        jlblSubtotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblSubtotal.setForeground(new java.awt.Color(102, 102, 102));
        jlblSubtotal.setText("Subtotal:");
        jPanel3.add(jlblSubtotal);
        jlblSubtotal.setBounds(450, 440, 70, 15);

        jlblIva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblIva.setForeground(new java.awt.Color(102, 102, 102));
        jlblIva.setText("IVA:");
        jPanel3.add(jlblIva);
        jlblIva.setBounds(453, 460, 70, 20);

        jlblTotalPago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblTotalPago.setForeground(new java.awt.Color(102, 102, 102));
        jlblTotalPago.setText("Total a pagar:");
        jPanel3.add(jlblTotalPago);
        jlblTotalPago.setBounds(450, 484, 90, 20);

        txtSubtotalCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalCPActionPerformed(evt);
            }
        });
        jPanel3.add(txtSubtotalCP);
        txtSubtotalCP.setBounds(540, 430, 61, 30);

        txtTotalPagarCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarCPActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotalPagarCP);
        txtTotalPagarCP.setBounds(541, 482, 61, 30);

        labelIcon8.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);

        labelIcon9.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon9.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        labelIcon8.add(labelIcon9);
        labelIcon9.setBounds(580, 680, 30, 30);

        jPanel3.add(labelIcon8);
        labelIcon8.setBounds(548, 126, 30, 30);

        labelIcon14.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon14.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);

        labelIcon15.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon15.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        labelIcon14.add(labelIcon15);
        labelIcon15.setBounds(580, 680, 30, 30);

        jPanel3.add(labelIcon14);
        labelIcon14.setBounds(548, 210, 30, 30);

        lblNroFactura.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNroFactura.setForeground(new java.awt.Color(102, 102, 102));
        lblNroFactura.setText("Nro Compra:");
        jPanel3.add(lblNroFactura);
        lblNroFactura.setBounds(190, 85, 80, 30);

        txtnroCompraCP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnroCompraCP.setForeground(new java.awt.Color(102, 102, 102));
        txtnroCompraCP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtnroCompraCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnroCompraCPMouseClicked(evt);
            }
        });
        txtnroCompraCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnroCompraCPActionPerformed(evt);
            }
        });
        txtnroCompraCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnroCompraCPKeyTyped(evt);
            }
        });
        jPanel3.add(txtnroCompraCP);
        txtnroCompraCP.setBounds(310, 91, 180, 18);

        rSLabelFecha1.setForeground(new java.awt.Color(102, 102, 102));
        rSLabelFecha1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(rSLabelFecha1);
        rSLabelFecha1.setBounds(560, 85, 138, 30);

        lblFormaPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFormaPago.setForeground(new java.awt.Color(102, 102, 102));
        lblFormaPago.setText("FormaPago:");
        jPanel3.add(lblFormaPago);
        lblFormaPago.setBounds(20, 430, 100, 30);

        checkBoxIVACP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkBoxIVACP.setForeground(new java.awt.Color(102, 102, 102));
        checkBoxIVACP.setText("14%");
        checkBoxIVACP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIVACPActionPerformed(evt);
            }
        });
        jPanel3.add(checkBoxIVACP);
        checkBoxIVACP.setBounds(541, 460, 61, 18);

        btnBuscarCedulaCP1.setBackground(new java.awt.Color(204, 0, 255));
        btnBuscarCedulaCP1.setText("Buscar");
        btnBuscarCedulaCP1.setColorHover(new java.awt.Color(102, 102, 102));
        btnBuscarCedulaCP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCedulaCP1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarCedulaCP1);
        btnBuscarCedulaCP1.setBounds(584, 126, 82, 22);

        txtIdProveedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIdProveedor.setForeground(new java.awt.Color(102, 102, 102));
        txtIdProveedor.setBorder(null);
        txtIdProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdProveedorMouseClicked(evt);
            }
        });
        txtIdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProveedorActionPerformed(evt);
            }
        });
        jPanel3.add(txtIdProveedor);
        txtIdProveedor.setBounds(790, 129, 48, 17);

        jlblSubtotal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlblSubtotal1.setForeground(new java.awt.Color(102, 102, 102));
        jlblSubtotal1.setText("Cantidad:");
        jPanel3.add(jlblSubtotal1);
        jlblSubtotal1.setBounds(190, 222, 59, 15);

        txtCodProductoCP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCodProductoCP.setForeground(new java.awt.Color(102, 102, 102));
        txtCodProductoCP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtCodProductoCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodProductoCPMouseClicked(evt);
            }
        });
        txtCodProductoCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProductoCPActionPerformed(evt);
            }
        });
        txtCodProductoCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodProductoCPKeyTyped(evt);
            }
        });
        jPanel3.add(txtCodProductoCP);
        txtCodProductoCP.setBounds(310, 190, 180, 18);

        btnLimpiar.setBackground(new java.awt.Color(0, 102, 51));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpiar);
        btnLimpiar.setBounds(100, 500, 130, 30);

        labelIcon1.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CACHED);
        labelIcon1.setInheritsPopupMenu(true);
        jPanel3.add(labelIcon1);
        labelIcon1.setBounds(70, 500, 30, 30);

        lblAvisoTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoTotal.setText("*");
        jPanel3.add(lblAvisoTotal);
        lblAvisoTotal.setBounds(610, 490, 20, 14);

        lblAvisoCompra.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCompra.setText("*");
        jPanel3.add(lblAvisoCompra);
        lblAvisoCompra.setBounds(490, 90, 20, 14);

        lblAvisoCedula.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCedula.setText("*");
        jPanel3.add(lblAvisoCedula);
        lblAvisoCedula.setBounds(490, 120, 20, 14);

        lblAvisoProveedor.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoProveedor.setText("*");
        jPanel3.add(lblAvisoProveedor);
        lblAvisoProveedor.setBounds(490, 150, 20, 14);

        lblAvisoCantidad.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCantidad.setText("*");
        jPanel3.add(lblAvisoCantidad);
        lblAvisoCantidad.setBounds(490, 220, 20, 14);

        lblAvisoSubtotal.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoSubtotal.setText("*");
        jPanel3.add(lblAvisoSubtotal);
        lblAvisoSubtotal.setBounds(610, 430, 20, 14);

        txtCantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(102, 102, 102));
        txtCantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadMouseClicked(evt);
            }
        });
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel3.add(txtCantidad);
        txtCantidad.setBounds(310, 220, 180, 18);

        lblAvisoCodigo.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCodigo.setText("*");
        jPanel3.add(lblAvisoCodigo);
        lblAvisoCodigo.setBounds(490, 190, 20, 14);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tblProductoCP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductoCP.setBackgoundHead(new java.awt.Color(102, 0, 102));
        jScrollPane3.setViewportView(tblProductoCP);

        jTabbedPane1.addTab("Factura", jScrollPane3);

        jPanel6.setLayout(new java.awt.BorderLayout());

        tbtDetalleCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbtDetalleCompra.setBackgoundHead(new java.awt.Color(102, 0, 102));
        jScrollPane1.setViewportView(tbtDetalleCompra);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Más detalles", jPanel6);

        jPanel3.add(jTabbedPane1);
        jTabbedPane1.setBounds(60, 250, 680, 170);

        btnTarjeta.setBackground(new java.awt.Color(51, 102, 0));
        btnTarjeta.setText("T. Débito/Crédito");
        btnTarjeta.setColorHover(new java.awt.Color(102, 102, 102));
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });
        jPanel3.add(btnTarjeta);
        btnTarjeta.setBounds(270, 430, 160, 30);

        btnEfectivo1.setBackground(new java.awt.Color(102, 0, 51));
        btnEfectivo1.setText("Efectivo");
        btnEfectivo1.setColorHover(new java.awt.Color(102, 102, 102));
        btnEfectivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivo1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEfectivo1);
        btnEfectivo1.setBounds(130, 430, 130, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(100, 150, 850, 550);

        rSLabelFecha2.setForeground(new java.awt.Color(102, 102, 102));
        rSLabelFecha2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(rSLabelFecha2);
        rSLabelFecha2.setBounds(560, 10, 200, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1038, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        AdministrarProveedor adminProveedor = new AdministrarProveedor();
        this.dispose();
        adminProveedor.setVisible(true);
        adminProveedor.setLocationRelativeTo(null);


    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        AdministrarPersonas adminPersonas = new AdministrarPersonas();
        this.dispose();
        adminPersonas.setVisible(true);
        adminPersonas.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        AdministrarProducto adminProducto = new AdministrarProducto();
        this.dispose();
        adminProducto.setVisible(true);
        adminProducto.setLocationRelativeTo(null);


    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MenuPrincipalAdministrador mpa = new MenuPrincipalAdministrador();
        dispose();
        mpa.setLocationRelativeTo(null);
        mpa.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void bntCalcularIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularIvaActionPerformed
        if (txtSubtotalCP.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese los productos que desea comprar");
        } else {
            calcularIva();
        }


    }//GEN-LAST:event_bntCalcularIvaActionPerformed

    private void btnBuscarCodProductoCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodProductoCPActionPerformed
        if (txtCodProductoCP.getText().equals("") || txtCantidad.getText().equals("")) {
            lblAvisoCodigo.setVisible(true);
            lblAvisoCantidad.setVisible(true);
            JOptionPane.showMessageDialog(null, "Por favor, ingrese el código de producto y la cantidad");
        } else {
            if (controles.validarNumeroEntero(txtCodProductoCP.getText())) {
                if (controles.validarNumeroEntero(txtCantidad.getText())) {
                    producto = cdao.buscarProductoCompra(txtCodProductoCP.getText(), Integer.valueOf(txtCantidad.getText()));
                    listaProductos.add(producto);
                    calcularSubtotal();
                    txtSubtotalCP.setText(String.valueOf(subtotal));
                    mostrarTabla();
                    cdao.actualizarStockBD(txtCodProductoCP.getText(), Integer.valueOf(txtCantidad.getText()));
                } else {
                    JOptionPane.showMessageDialog(null, "Cantidad Incorrecto");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Código del Producto Incorrecto");
            }
        }
    }//GEN-LAST:event_btnBuscarCodProductoCPActionPerformed

    private void txtCedulaCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaCPMouseClicked

    }//GEN-LAST:event_txtCedulaCPMouseClicked

    private void txtProveedorCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtProveedorCPMouseClicked

    }//GEN-LAST:event_txtProveedorCPMouseClicked

    private void btnGuardarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCPActionPerformed

        if (camposVacios()) {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar");

        } else {
            if (controles.Numero(txtnroCompraCP.getText())) {
                CompraDAO comDao = new CompraDAO();
                Proveedor prove = new Proveedor();
                String nroCompra = txtnroCompraCP.getText();
                boolean iva = checkBoxIVACP.isSelected();
                String fPago = formaPago;
                double subtotal = Double.parseDouble(txtSubtotalCP.getText());
                double total = Double.parseDouble(txtTotalPagarCP.getText());
                String idAci = "";
                Boolean estado = false;
                comDao.insertarCompra(nroCompra, fecha, iva, fPago, subtotal, total, Long.valueOf(txtIdProveedor.getText()), idAci, estado);
                mostrarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Numero de compra incorrecto");
            }
        }
    }//GEN-LAST:event_btnGuardarCPActionPerformed


    private void txtnroCompraCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnroCompraCPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnroCompraCPMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMover.FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMover.FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_formMouseDragged

    private void txtTotalPagarCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarCPActionPerformed

    }//GEN-LAST:event_txtTotalPagarCPActionPerformed

    private void checkBoxIVACPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxIVACPActionPerformed
               
    }//GEN-LAST:event_checkBoxIVACPActionPerformed

    private void btnBuscarCedulaCP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCedulaCP1ActionPerformed
        if (txtCedulaCP.getText().equals("") || txtCedulaCP.getText().length() != 10) {
            lblAvisoCedula.setVisible(true);
            JOptionPane.showMessageDialog(null, "Por favor, ingrese la cédula del Proveedor");
        } else {
            mostrarNombreProveedor(txtCedulaCP.getText());
        }
    }//GEN-LAST:event_btnBuscarCedulaCP1ActionPerformed

    private void txtIdProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdProveedorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProveedorMouseClicked

    private void txtIdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProveedorActionPerformed

    private void txtCodProductoCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodProductoCPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProductoCPMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtProveedorCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedorCPActionPerformed

    private void txtCedulaCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaCPActionPerformed

    private void txtCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadMouseClicked

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtSubtotalCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalCPActionPerformed
        txtSubtotalCP.setEnabled(false);
    }//GEN-LAST:event_txtSubtotalCPActionPerformed

    private void txtnroCompraCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnroCompraCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnroCompraCPActionPerformed

    private void txtnroCompraCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnroCompraCPKeyTyped
        char caracteres = evt.getKeyChar();

        if (caracteres < '0' || caracteres > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_txtnroCompraCPKeyTyped

    private void txtCedulaCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaCPKeyTyped
        char caracteres = evt.getKeyChar();

        if (caracteres < '0' || caracteres > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_txtCedulaCPKeyTyped

    private void txtCodProductoCPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProductoCPKeyTyped
        char caracteres = evt.getKeyChar();

        if (caracteres < '0' || caracteres > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_txtCodProductoCPKeyTyped

    private void txtCodProductoCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProductoCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProductoCPActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char caracteres = evt.getKeyChar();

        if (caracteres < '0' || caracteres > '9') {
            evt.consume();
        }

    }//GEN-LAST:event_txtCantidadKeyTyped

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        Tarjeta = true;
        formaPago = "Tarjeta C/D";
    }//GEN-LAST:event_btnTarjetaActionPerformed

    private void btnEfectivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivo1ActionPerformed
        efectivo = true;
        formaPago = "Efectivo";
    }//GEN-LAST:event_btnEfectivo1ActionPerformed

    private void btnCompraProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraProveedorActionPerformed
        CompraProveedor cp = new CompraProveedor();
        this.dispose();
        cp.setVisible(true);
        cp.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCompraProveedorActionPerformed

    private void calcularIva() {
        double subtotal = Double.parseDouble(txtSubtotalCP.getText());
        boolean iva = checkBoxIVACP.isSelected();
        double total;
        double totaliva;
        double ivaT;
        double resta;
        if (iva == true) {
            ivaT = 1.14;
            totaliva = subtotal / ivaT;
            resta = subtotal - totaliva;
            total = subtotal + resta;
            double roundDbl = Math.round(total * 100.0) / 100.0;
            txtTotalPagarCP.setText(String.valueOf(roundDbl));

        } else {
            total = subtotal;
            txtTotalPagarCP.setText(String.valueOf(total));
        }
    }

    private void mostrarTabla() {
        cdao.listarProducto(tblProductoCP, listaProductos);

    }

    private void mostrarNombreProveedor(String cedula) {
        nombre = cdao.listarProveedor(cedula);
        txtProveedorCP.setText(nombre);
        id = cdao.retornarId(cedula);
        txtIdProveedor.setText(id);
    }

    public void calcularSubtotal() {
        subtotal += cdao.calcularSubtotal(listaProductos, Integer.parseInt(txtCantidad.getText()));
    }

    public boolean camposVacios() {
        if (txtnroCompraCP.getText().equals("") || txtCedulaCP.getText().equals("") || txtProveedorCP.getText().equals("")
                || txtCodProductoCP.getText().equals("") || txtCantidad.getText().equals("") || formaPago.equals("")
                || txtSubtotalCP.getText().equals("") || txtTotalPagarCP.getText().equals("")) {
            txtIdProveedor.setVisible(true);
            lblAvisoCompra.setVisible(true);
            lblAvisoCedula.setVisible(true);
            lblAvisoProveedor.setVisible(true);
            lblAvisoCodigo.setVisible(true);
            lblAvisoCantidad.setVisible(true);
            lblAvisoSubtotal.setVisible(true);
            lblAvisoTotal.setVisible(true);
            return true;
        } else {
            return false;
        }

    }
    public void guardarDetalle(){
        Producto codP = cdao.buscarProductoC(nombre);
      //  int codigoP = Integer.parseInt(codP);
        for (int i = 0; i < tblProductoCP.getRowCount(); i++) {
            int cdp = Integer.parseInt(tblProductoCP.getValueAt(i, 0).toString());
            double pre = Integer.parseInt(tblProductoCP.getValueAt(i, 3).toString());
            
            
        }
      
        
                }
    private void limpiar() {

        txtnroCompraCP.setText("");
        txtCedulaCP.setText("");
        txtProveedorCP.setText("");
        txtCodProductoCP.setText("");
        txtCantidad.setText("");
        txtSubtotalCP.setText("");
        txtTotalPagarCP.setText("");
        txtIdProveedor.setVisible(false);
        lblAvisoCompra.setVisible(false);
        lblAvisoCedula.setVisible(false);
        lblAvisoProveedor.setVisible(false);
        lblAvisoCodigo.setVisible(false);
        lblAvisoCantidad.setVisible(false);
        lblAvisoSubtotal.setVisible(false);
        lblAvisoTotal.setVisible(false);
        listaProductos.removeAll(listaProductos);
        tblProductoCP.removeAll();
        mostrarTabla();
        limpiaTabla();
    }

    void limpiaTabla() {
        DefaultTableModel temp;
        try {
            temp = (DefaultTableModel) tbtDetalleCompra.getModel();
            int a = temp.getRowCount();
            for (int i = 0; i <= a; i++) {
                temp.removeRow(i);
                temp.removeRow(i);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover bntCalcularIva;
    private rojerusan.RSButtonHover btnBuscarCedulaCP1;
    private rojerusan.RSButtonHover btnBuscarCodProductoCP;
    private newscomponents.RSButtonBigIcon_new btnCompraProveedor;
    private rojerusan.RSButtonHover btnEfectivo1;
    private rojerusan.RSButtonHover btnGuardarCP;
    private rojerusan.RSButtonHover btnLimpiar;
    private RSMaterialComponent.RSButtonIconDos btnMinimizar;
    private newscomponents.RSButtonBigIcon_new btnProducto;
    private newscomponents.RSButtonBigIcon_new btnProveedor;
    private newscomponents.RSButtonBigIcon_new btnRegistrar;
    private RSMaterialComponent.RSButtonCustomIcon btnRegresar;
    private RSMaterialComponent.RSButtonIconDos btnSalir;
    private rojerusan.RSButtonHover btnTarjeta;
    private javax.swing.JCheckBox checkBoxIVACP;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jlblIva;
    private javax.swing.JLabel jlblSubtotal;
    private javax.swing.JLabel jlblSubtotal1;
    private javax.swing.JLabel jlblTotalPago;
    private necesario.LabelIcon labelIcon1;
    private necesario.LabelIcon labelIcon14;
    private necesario.LabelIcon labelIcon15;
    private necesario.LabelIcon labelIcon5;
    private necesario.LabelIcon labelIcon8;
    private necesario.LabelIcon labelIcon9;
    private javax.swing.JLabel lblAvisoCantidad;
    private javax.swing.JLabel lblAvisoCedula;
    private javax.swing.JLabel lblAvisoCodigo;
    private javax.swing.JLabel lblAvisoCompra;
    private javax.swing.JLabel lblAvisoProveedor;
    private javax.swing.JLabel lblAvisoSubtotal;
    private javax.swing.JLabel lblAvisoTotal;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFormaPago;
    private javax.swing.JLabel lblNroFactura;
    private javax.swing.JLabel lblProveedor;
    private rojeru_san.rsdate.RSLabelFecha rSLabelFecha1;
    private rojeru_san.rsdate.RSLabelFecha rSLabelFecha2;
    private rojeru_san.rsdate.RSLabelHora rSLabelHora1;
    private rojeru_san.rslabel.RSLabelImage rSLabelImage1;
    private necesario.RSLabelImage rSLabelImage2;
    private necesario.RSLabelImage rSLabelImage4;
    private RSMaterialComponent.RSTableMetro tblProductoCP;
    private RSMaterialComponent.RSTableMetro tbtDetalleCompra;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCedulaCP;
    private javax.swing.JTextField txtCodProductoCP;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtProveedorCP;
    private javax.swing.JTextField txtSubtotalCP;
    private javax.swing.JTextField txtTotalPagarCP;
    private javax.swing.JTextField txtnroCompraCP;
    // End of variables declaration//GEN-END:variables
}
