/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DAO.Aci_Servicio_Web;
import controlador.utilidades.Controladores;
import controlador.DAO.DetalleFacturaDAO;
import controlador.DAO.FacturaDAO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Persona;
import modelo.Producto;

/**
 *
 * @author Juan Armijos, Cristian Capa, Maria Castillo, Kelly Preciado
 */
public class Factura extends javax.swing.JFrame {

    Controladores controles = new Controladores();
    private FacturaDAO fac = new FacturaDAO();
    private DetalleFacturaDAO dDAO = new DetalleFacturaDAO();
    /**
     * Creates new form Factura
     */

    ArrayList<Producto> listaProductos = new ArrayList<Producto>();
    Date fecha = new Date();
    String nombre = "";
    String id = "";
    Double subtotal = 0.0;
    Boolean efectivo = false;
    Boolean Tarjeta = false;
    String formaPago = "";

    Producto produc = new Producto();

    public Factura() {

        initComponents();
        this.setLocationRelativeTo(null);
        txtidPersona.setVisible(false);
        lblAvisoFactura.setVisible(false);
        lblAvisoCedula.setVisible(false);
        lblAvisoCliente.setVisible(false);
        lblAvisoCodigo.setVisible(false);
        lblAvisoCantidad.setVisible(false);
        lblAvisoSubtotal.setVisible(false);
        lblAvisoTotal.setVisible(false);

    }

    void limpiaTabla() {
        DefaultTableModel temp;
        try {
            temp = (DefaultTableModel) tbtDetalleFactura.getModel();
            int a = temp.getRowCount();
            for (int i = 0; i <= a; i++) {
                temp.removeRow(i);
                temp.removeRow(i);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void mostrarTabla() {

        fac.listarProducto(tablaFactura, listaProductos);
    }

    private void mostrarNombreCliente(String cedula) {
        nombre = fac.listarPersona(cedula);
        txtnombreCliente.setText(nombre);
        id = fac.retornarId(cedula);
        txtidPersona.setText(id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rSLabelImage5 = new necesario.RSLabelImage();
        btnFactura = new newscomponents.RSButtonBigIcon_new();
        btnRegistrar = new newscomponents.RSButtonBigIcon_new();
        btnGuardar1 = new rojerusan.RSButtonHover();
        labelIcon13 = new necesario.LabelIcon();
        btnMinimizar1 = new RSMaterialComponent.RSButtonIconDos();
        btnSalir1 = new RSMaterialComponent.RSButtonIconDos();
        rSLabelImage3 = new necesario.RSLabelImage();
        rSLabelHora2 = new rojeru_san.rsdate.RSLabelHora();
        rSLabelFecha2 = new rojeru_san.rsdate.RSLabelFecha();
        jLabel25 = new javax.swing.JLabel();
        btnRegresar = new newscomponents.RSButtonIcon_new();
        txtidPersona = new javax.swing.JTextField();
        txtnombreCliente = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelIcon8 = new necesario.LabelIcon();
        labelIcon9 = new necesario.LabelIcon();
        btnCalcular = new rojerusan.RSButtonHover();
        btnBuscarProducto1 = new rojerusan.RSButtonHover();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        rSLabelFecha1 = new rojeru_san.rsdate.RSLabelFecha();
        checkBoxIVA = new javax.swing.JCheckBox();
        btnBuscarCliente2 = new rojerusan.RSButtonHover();
        txtFactura = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnLimpiar = new rojerusan.RSButtonHover();
        labelIcon14 = new necesario.LabelIcon();
        lblAvisoCedula = new javax.swing.JLabel();
        lblAvisoTotal = new javax.swing.JLabel();
        lblAvisoFactura = new javax.swing.JLabel();
        lblAvisoCliente = new javax.swing.JLabel();
        lblAvisoCodigo = new javax.swing.JLabel();
        lblAvisoCantidad = new javax.swing.JLabel();
        lblAvisoSubtotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaFactura = new RSMaterialComponent.RSTableMetro();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtDetalleFactura = new RSMaterialComponent.RSTableMetro();
        btnTarjeta = new rojerusan.RSButtonHover();
        btnEfectivo1 = new rojerusan.RSButtonHover();
        btnVerificarPago = new rojerusan.RSButtonHover();
        txtCodACI = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtIdACI = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setLayout(null);

        rSLabelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSistemaFinal.jpg"))); // NOI18N
        jPanel4.add(rSLabelImage5);
        rSLabelImage5.setBounds(600, 10, 160, 70);

        btnFactura.setBackground(new java.awt.Color(0, 153, 102));
        btnFactura.setText("Factura");
        btnFactura.setBgHover(new java.awt.Color(102, 102, 102));
        btnFactura.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SHOPPING_CART);
        btnFactura.setSizeIcon(50.0F);
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        jPanel4.add(btnFactura);
        btnFactura.setBounds(370, 0, 120, 80);

        btnRegistrar.setBackground(new java.awt.Color(0, 153, 102));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBgHover(new java.awt.Color(102, 102, 102));
        btnRegistrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PERSON_ADD);
        btnRegistrar.setSizeIcon(50.0F);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrar);
        btnRegistrar.setBounds(220, 0, 120, 80);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 50, 1160, 90);

        btnGuardar1.setBackground(new java.awt.Color(0, 204, 51));
        btnGuardar1.setText("Guardar");
        btnGuardar1.setColorHover(new java.awt.Color(102, 102, 102));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar1);
        btnGuardar1.setBounds(380, 670, 130, 30);

        labelIcon13.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon13.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        jPanel3.add(labelIcon13);
        labelIcon13.setBounds(340, 670, 30, 30);

        btnMinimizar1.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimizar1.setForeground(new java.awt.Color(102, 102, 102));
        btnMinimizar1.setBackgroundHover(new java.awt.Color(0, 102, 204));
        btnMinimizar1.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnMinimizar1.setForegroundText(new java.awt.Color(102, 102, 102));
        btnMinimizar1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REMOVE);
        btnMinimizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnMinimizar1);
        btnMinimizar1.setBounds(700, 0, 40, 40);

        btnSalir1.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir1.setForeground(new java.awt.Color(102, 102, 102));
        btnSalir1.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnSalir1.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnSalir1.setForegroundText(new java.awt.Color(102, 102, 102));
        btnSalir1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalir1);
        btnSalir1.setBounds(740, 0, 40, 40);

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSistemaFinal.jpg"))); // NOI18N
        jPanel3.add(rSLabelImage3);
        rSLabelImage3.setBounds(10, 10, 50, 40);

        rSLabelHora2.setForeground(new java.awt.Color(102, 102, 102));
        rSLabelHora2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(rSLabelHora2);
        rSLabelHora2.setBounds(540, 0, 140, 40);

        rSLabelFecha2.setForeground(new java.awt.Color(102, 102, 102));
        rSLabelFecha2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(rSLabelFecha2);
        rSLabelFecha2.setBounds(420, 0, 130, 40);

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("ELECTROCASA");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(70, 10, 190, 30);

        btnRegresar.setBackground(new java.awt.Color(0, 204, 51));
        btnRegresar.setText("Regresar");
        btnRegresar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REPLAY);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegresar);
        btnRegresar.setBounds(270, 10, 120, 30);

        txtidPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtidPersona.setForeground(new java.awt.Color(102, 102, 102));
        txtidPersona.setBorder(null);
        txtidPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtidPersonaMouseClicked(evt);
            }
        });
        txtidPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidPersonaActionPerformed(evt);
            }
        });
        jPanel3.add(txtidPersona);
        txtidPersona.setBounds(580, 180, 160, 30);

        txtnombreCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnombreCliente.setForeground(new java.awt.Color(102, 102, 102));
        txtnombreCliente.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtnombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombreClienteMouseClicked(evt);
            }
        });
        txtnombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreClienteActionPerformed(evt);
            }
        });
        jPanel3.add(txtnombreCliente);
        txtnombreCliente.setBounds(190, 240, 160, 30);

        txtCedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(102, 102, 102));
        txtCedula.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCedulaMouseClicked(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel3.add(txtCedula);
        txtCedula.setBounds(190, 200, 160, 30);

        txtCantidadProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCantidadProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtCantidadProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtCantidadProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadProductoMouseClicked(evt);
            }
        });
        txtCantidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadProductoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCantidadProducto);
        txtCantidadProducto.setBounds(190, 320, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Cantidad:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(40, 320, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText(" Cliente:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 240, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Cédula Cliente:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 200, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Nro Factura:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(40, 160, 110, 30);

        labelIcon8.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        jPanel3.add(labelIcon8);
        labelIcon8.setBounds(390, 190, 30, 30);

        labelIcon9.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon9.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        jPanel3.add(labelIcon9);
        labelIcon9.setBounds(390, 290, 30, 30);

        btnCalcular.setBackground(new java.awt.Color(102, 153, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setColorHover(new java.awt.Color(102, 102, 102));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel3.add(btnCalcular);
        btnCalcular.setBounds(630, 580, 110, 30);

        btnBuscarProducto1.setBackground(new java.awt.Color(204, 0, 255));
        btnBuscarProducto1.setText("Buscar");
        btnBuscarProducto1.setColorHover(new java.awt.Color(102, 102, 102));
        btnBuscarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProducto1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarProducto1);
        btnBuscarProducto1.setBounds(420, 290, 100, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("COD:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 640, 50, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Subtotal:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(440, 550, 70, 30);

        txtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSubtotal.setForeground(new java.awt.Color(102, 102, 102));
        txtSubtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtSubtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSubtotalMouseClicked(evt);
            }
        });
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        jPanel3.add(txtSubtotal);
        txtSubtotal.setBounds(510, 550, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Iva:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(440, 580, 70, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Total:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(440, 610, 70, 30);

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(102, 102, 102));
        txtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalMouseClicked(evt);
            }
        });
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotal);
        txtTotal.setBounds(510, 610, 90, 30);

        rSLabelFecha1.setForeground(new java.awt.Color(102, 102, 102));
        rSLabelFecha1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(rSLabelFecha1);
        rSLabelFecha1.setBounds(440, 140, 120, 30);

        checkBoxIVA.setText("14%");
        checkBoxIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIVAActionPerformed(evt);
            }
        });
        jPanel3.add(checkBoxIVA);
        checkBoxIVA.setBounds(510, 590, 49, 23);

        btnBuscarCliente2.setBackground(new java.awt.Color(204, 0, 255));
        btnBuscarCliente2.setText("Buscar");
        btnBuscarCliente2.setColorHover(new java.awt.Color(102, 102, 102));
        btnBuscarCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCliente2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarCliente2);
        btnBuscarCliente2.setBounds(420, 200, 100, 20);

        txtFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFactura.setForeground(new java.awt.Color(102, 102, 102));
        txtFactura.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFacturaMouseClicked(evt);
            }
        });
        jPanel3.add(txtFactura);
        txtFactura.setBounds(190, 150, 160, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Código Producto:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(40, 280, 130, 30);

        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoMouseClicked(evt);
            }
        });
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodigo);
        txtCodigo.setBounds(190, 280, 160, 30);

        btnLimpiar.setBackground(new java.awt.Color(0, 102, 51));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setColorHover(new java.awt.Color(102, 102, 102));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpiar);
        btnLimpiar.setBounds(190, 670, 130, 30);

        labelIcon14.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon14.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        jPanel3.add(labelIcon14);
        labelIcon14.setBounds(150, 670, 30, 30);

        lblAvisoCedula.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCedula.setText("*");
        jPanel3.add(lblAvisoCedula);
        lblAvisoCedula.setBounds(360, 200, 20, 14);

        lblAvisoTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoTotal.setText("*");
        jPanel3.add(lblAvisoTotal);
        lblAvisoTotal.setBounds(600, 620, 30, 14);

        lblAvisoFactura.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoFactura.setText("*");
        jPanel3.add(lblAvisoFactura);
        lblAvisoFactura.setBounds(360, 160, 30, 14);

        lblAvisoCliente.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCliente.setText("*");
        jPanel3.add(lblAvisoCliente);
        lblAvisoCliente.setBounds(360, 240, 30, 14);

        lblAvisoCodigo.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCodigo.setText("*");
        jPanel3.add(lblAvisoCodigo);
        lblAvisoCodigo.setBounds(360, 280, 30, 14);

        lblAvisoCantidad.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCantidad.setText("*");
        jPanel3.add(lblAvisoCantidad);
        lblAvisoCantidad.setBounds(360, 320, 30, 14);

        lblAvisoSubtotal.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoSubtotal.setText("*");
        jPanel3.add(lblAvisoSubtotal);
        lblAvisoSubtotal.setBounds(600, 580, 30, 14);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaFactura.setBackgoundHead(new java.awt.Color(102, 0, 102));
        jScrollPane3.setViewportView(tablaFactura);

        jTabbedPane1.addTab("Factura", jScrollPane3);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tbtDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbtDetalleFactura.setBackgoundHead(new java.awt.Color(102, 0, 102));
        jScrollPane1.setViewportView(tbtDetalleFactura);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Más detalles", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel1);
        jPanel1.setBounds(40, 360, 690, 190);

        btnTarjeta.setBackground(new java.awt.Color(51, 102, 0));
        btnTarjeta.setText("T. Débito/Crédito");
        btnTarjeta.setColorHover(new java.awt.Color(102, 102, 102));
        btnTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarjetaActionPerformed(evt);
            }
        });
        jPanel3.add(btnTarjeta);
        btnTarjeta.setBounds(250, 550, 160, 30);

        btnEfectivo1.setBackground(new java.awt.Color(102, 0, 51));
        btnEfectivo1.setText("Efectivo");
        btnEfectivo1.setColorHover(new java.awt.Color(102, 102, 102));
        btnEfectivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivo1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnEfectivo1);
        btnEfectivo1.setBounds(110, 550, 130, 30);

        btnVerificarPago.setBackground(new java.awt.Color(102, 153, 255));
        btnVerificarPago.setText("Verificar pago");
        btnVerificarPago.setColorHover(new java.awt.Color(102, 102, 102));
        btnVerificarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarPagoActionPerformed(evt);
            }
        });
        jPanel3.add(btnVerificarPago);
        btnVerificarPago.setBounds(250, 630, 160, 30);

        txtCodACI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        jPanel3.add(txtCodACI);
        txtCodACI.setBounds(20, 590, 410, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Forma Pago:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 550, 100, 20);

        txtIdACI.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        jPanel3.add(txtIdACI);
        txtIdACI.setBounds(60, 630, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        Factura fact = new Factura();
        this.dispose();
        fact.setVisible(true);
        fact.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnMinimizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizar1ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizar1ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtidPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidPersonaMouseClicked

    }//GEN-LAST:event_txtidPersonaMouseClicked

    private void txtnombreClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreClienteMouseClicked

    private void txtnombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreClienteActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreClienteActionPerformed

    private void txtCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaMouseClicked

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCantidadProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoMouseClicked

    private void txtCantidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //subtotal();
        if (txtSubtotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese los productos que desea vender");

        } else {
            calcularIva();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnBuscarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProducto1ActionPerformed
        if (txtCodigo.getText().equals("") || txtCantidadProducto.getText().equals("")) {
            lblAvisoCodigo.setVisible(true);
            lblAvisoCantidad.setVisible(true);
            JOptionPane.showMessageDialog(null, "Por favor, ingrese el código, cantidad del producto");
        } else {
            if (controles.validarNumeroEntero(txtCodigo.getText())) {
                if (controles.validarNumeroEntero(txtCantidadProducto.getText())) {
                    produc = fac.buscarProductoFactura(txtCodigo.getText(), Integer.valueOf(txtCantidadProducto.getText()));
                    if (produc.getIdProducto() == null) {
                        JOptionPane.showMessageDialog(null, "Código no encontrado");
                    } else {
                        listaProductos.add(produc);
                        calcularSubtotal();
                        txtSubtotal.setText(String.valueOf(subtotal));
                        mostrarTabla();
                        fac.actualizarStockBD(txtCodigo.getText(), Integer.valueOf(txtCantidadProducto.getText()));

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Cantidad Incorrecto");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Código del Producto Incorrecto");
            }

        }

    }//GEN-LAST:event_btnBuscarProducto1ActionPerformed

    private void txtSubtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSubtotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalMouseClicked

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        txtSubtotal.setEnabled(false);

    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMouseClicked

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    public boolean camposVacios() {
        if (txtFactura.getText().equals("") || txtCedula.getText().equals("") || txtnombreCliente.getText().equals("")
                || txtCodigo.getText().equals("") || txtCantidadProducto.getText().equals("")
                || txtSubtotal.getText().equals("") || txtTotal.getText().equals("")) {

            lblAvisoCedula.setVisible(true);
            lblAvisoCliente.setVisible(true);
            lblAvisoCodigo.setVisible(true);
            lblAvisoCantidad.setVisible(true);
            lblAvisoSubtotal.setVisible(true);
            lblAvisoTotal.setVisible(true);
            lblAvisoFactura.setVisible(true);
            return true;
        } else {
            return false;
        }
    }
    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        FacturaDAO fac1 = new FacturaDAO();
        if (camposVacios()) {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar");
        } else {
            if (controles.Numero(txtFactura.getText())) {
                Date fecha = new Date();
                Persona persona = new Persona();
                persona.setIdPersona(Long.valueOf(txtidPersona.getText()));
                String nroFactura = txtFactura.getText();
                Boolean iva = checkBoxIVA.isSelected();
                String formaPago = this.formaPago;
                String idAci = txtIdACI.getText();
                Boolean estado = true;
                double subtotal = Double.parseDouble(txtSubtotal.getText());
                double total = Double.parseDouble(txtTotal.getText());
                fac1.insertarFactura(fecha, formaPago, iva, nroFactura, subtotal, total, persona, idAci, estado);
                JOptionPane.showMessageDialog(rootPane, "Factura agregada");
                for (Producto listaProducto : listaProductos) {
                    dDAO.insertarDetalleFactura(listaProducto.getNombre(), listaProducto.getPrecio(), fac1.getFactura(), listaProducto);
                }
                mostrarTabla();
            } else {
                JOptionPane.showMessageDialog(null, "Numero de factura incorrecto");
            }
            dDAO.listarFactura(tbtDetalleFactura, fac1.getFactura().getIdFactura());
            mostrarTabla();
            formaPago = "";
        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMover.FiveCodMoverJFrame.MousePressed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMover.FiveCodMoverJFrame.MouseDraggedFrame(evt, this);

        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void checkBoxIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxIVAActionPerformed

    private void btnBuscarCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCliente2ActionPerformed
        if (txtCedula.getText().equals("") || txtCedula.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese la cédula del Cliente");
            lblAvisoCedula.setVisible(true);
        } else {
            mostrarNombreCliente(txtCedula.getText());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCliente2ActionPerformed

    private void txtFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFacturaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturaMouseClicked

    private void txtidPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidPersonaActionPerformed

    private void txtCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMouseClicked

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarjetaActionPerformed
        Tarjeta = true;
        formaPago = "Tarjeta C/D";
        String fac = "";
        Aci_Servicio_Web aci = new Aci_Servicio_Web();
        fac = aci.facturar(Double.valueOf(txtTotal.getText()));
        txtCodACI.setText(fac);
    }//GEN-LAST:event_btnTarjetaActionPerformed

    private void btnEfectivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivo1ActionPerformed
        efectivo = true;
        formaPago = "Efectivo";
    }//GEN-LAST:event_btnEfectivo1ActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        AdministrarPersonas adminPersonas = new AdministrarPersonas();
        this.dispose();
        adminPersonas.setVisible(true);
        adminPersonas.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVerificarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarPagoActionPerformed
        Aci_Servicio_Web aci = new Aci_Servicio_Web();
        try {
            aci.verificarPago(txtIdACI.getText());
            JOptionPane.showMessageDialog(null, "Pago realizado con exito");
        } catch (IOException ex) {
            Logger.getLogger(Factura.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnVerificarPagoActionPerformed
    private void calcularIva() {
        double subtotal = Double.parseDouble(txtSubtotal.getText());
        boolean iva = checkBoxIVA.isSelected();
        double total;
        double totaliva;
        double ivaT;
        double resta;
        if (iva == true) {
            ivaT = 1.14;
            totaliva = subtotal / ivaT;
            resta = subtotal - totaliva;
            total = subtotal + resta;
            double roundDbl = Math.round(total * 100.0) / 100.0;
            txtTotal.setText(String.valueOf(roundDbl));

        } else {
            total = subtotal;
            txtTotal.setText(String.valueOf(total));
        }
    }

    public void calcularSubtotal() {
        subtotal += fac.calcularSubtotal(listaProductos, Integer.parseInt(txtCantidadProducto.getText()));

    }

    private void limpiar() {
        txtFactura.setText("");
        txtCedula.setText("");
        txtnombreCliente.setText("");
        txtCodigo.setText("");
        txtCantidadProducto.setText("");
        txtSubtotal.setText("");
        txtTotal.setText("");

        lblAvisoCedula.setVisible(false);
        lblAvisoCliente.setVisible(false);
        lblAvisoCodigo.setVisible(false);
        lblAvisoCantidad.setVisible(false);
        lblAvisoSubtotal.setVisible(false);
        lblAvisoTotal.setVisible(false);
        lblAvisoFactura.setVisible(false);
        listaProductos.removeAll(listaProductos);
        tablaFactura.removeAll();
        limpiaTabla();
        mostrarTabla();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnBuscarCliente2;
    private rojerusan.RSButtonHover btnBuscarProducto1;
    private rojerusan.RSButtonHover btnCalcular;
    private rojerusan.RSButtonHover btnEfectivo1;
    private newscomponents.RSButtonBigIcon_new btnFactura;
    private rojerusan.RSButtonHover btnGuardar1;
    private rojerusan.RSButtonHover btnLimpiar;
    private RSMaterialComponent.RSButtonIconDos btnMinimizar1;
    private newscomponents.RSButtonBigIcon_new btnRegistrar;
    private newscomponents.RSButtonIcon_new btnRegresar;
    private RSMaterialComponent.RSButtonIconDos btnSalir1;
    private rojerusan.RSButtonHover btnTarjeta;
    private rojerusan.RSButtonHover btnVerificarPago;
    private javax.swing.JCheckBox checkBoxIVA;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private necesario.LabelIcon labelIcon13;
    private necesario.LabelIcon labelIcon14;
    private necesario.LabelIcon labelIcon8;
    private necesario.LabelIcon labelIcon9;
    private javax.swing.JLabel lblAvisoCantidad;
    private javax.swing.JLabel lblAvisoCedula;
    private javax.swing.JLabel lblAvisoCliente;
    private javax.swing.JLabel lblAvisoCodigo;
    private javax.swing.JLabel lblAvisoFactura;
    private javax.swing.JLabel lblAvisoSubtotal;
    private javax.swing.JLabel lblAvisoTotal;
    private rojeru_san.rsdate.RSLabelFecha rSLabelFecha1;
    private rojeru_san.rsdate.RSLabelFecha rSLabelFecha2;
    private rojeru_san.rsdate.RSLabelHora rSLabelHora2;
    private necesario.RSLabelImage rSLabelImage3;
    private necesario.RSLabelImage rSLabelImage5;
    private RSMaterialComponent.RSTableMetro tablaFactura;
    private RSMaterialComponent.RSTableMetro tbtDetalleFactura;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodACI;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtIdACI;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtidPersona;
    private javax.swing.JTextField txtnombreCliente;
    // End of variables declaration//GEN-END:variables
}
