/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.utilidades.Controladores;
import controlador.DAO.DetalleFacturaDAO;
import controlador.DAO.FacturaDAO;
import controlador.DAO.PersonaDAO;
import controlador.DAO.ProductoDAO;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Persona;
import modelo.Producto;

/**
 *
 * @author María Castillo
 */
public class Factura extends javax.swing.JFrame {

    Controladores controles = new Controladores();
    private FacturaDAO fac = new FacturaDAO();
    private ProductoDAO producto = new ProductoDAO();
    private PersonaDAO pe = new PersonaDAO();
    private DetalleFacturaDAO detalleFactura = new DetalleFacturaDAO();
    /**
     * Creates new form Factura
     */

    ArrayList<Producto> listaProductos = new ArrayList<Producto>();

    Date fecha = new Date();
    //String subtotal = "";
    String nombre = "";
    String id = "";
    Double subtotal = 0.0;

    Producto produc = new Producto();

    public Factura() {

        initComponents();
        this.setLocationRelativeTo(null);
        txtidPersona.setVisible(false);
        lblAvisoFactura.setVisible(false);
        lblAvisoCedula.setVisible(false);
        lblAvisoCliente.setVisible(false);
        lblAvisoCodigo.setVisible(false);
        lblAvisoCantidad.setVisible(false);
        lblAvisoFormaPago.setVisible(false);
        lblAvisoSubtotal.setVisible(false);
        lblAvisoTotal.setVisible(false);

    }

    private void mostrarTabla() {

        fac.listarProducto(tablaFactura, listaProductos);
        //System.out.println(listaProductos.size());
    }

    private void mostrarNombreCliente(String cedula) {
        nombre = fac.listarPersona(cedula);
        txtnombreCliente.setText(nombre);
        id = fac.retornarId(cedula);
        txtidPersona.setText(id);
    }

    public void limpiarCampos() {
        txtCedula.setText("");
        txtidPersona.setText("");
        txtSubtotal.setText("");
        txtTotal.setText("");
        txtnombreCliente.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rSLabelImage5 = new necesario.RSLabelImage();
        btnDetalleFactura = new newscomponents.RSButtonBigIcon_new();
        btnFactura = new newscomponents.RSButtonBigIcon_new();
        btnGuardar1 = new rojerusan.RSButtonHover();
        labelIcon13 = new necesario.LabelIcon();
        btnMinimizar1 = new RSMaterialComponent.RSButtonIconDos();
        btnSalir1 = new RSMaterialComponent.RSButtonIconDos();
        rSLabelImage3 = new necesario.RSLabelImage();
        rSLabelHora2 = new rojeru_san.rsdate.RSLabelHora();
        rSLabelFecha2 = new rojeru_san.rsdate.RSLabelFecha();
        jLabel25 = new javax.swing.JLabel();
        btnRegresar = new newscomponents.RSButtonIcon_new();
        txtidPersona = new javax.swing.JTextField();
        txtnombreCliente = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelIcon8 = new necesario.LabelIcon();
        labelIcon9 = new necesario.LabelIcon();
        btnCalcular = new rojerusan.RSButtonHover();
        btnBuscarProducto1 = new rojerusan.RSButtonHover();
        jLabel10 = new javax.swing.JLabel();
        txtFormaPago = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaFactura = new RSMaterialComponent.RSTableMetro();
        rSLabelFecha1 = new rojeru_san.rsdate.RSLabelFecha();
        checkBoxIVA = new javax.swing.JCheckBox();
        btnBuscarCliente2 = new rojerusan.RSButtonHover();
        txtFactura = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnLimpiar = new rojerusan.RSButtonHover();
        labelIcon14 = new necesario.LabelIcon();
        lblAvisoCedula = new javax.swing.JLabel();
        lblAvisoTotal = new javax.swing.JLabel();
        lblAvisoFactura = new javax.swing.JLabel();
        lblAvisoCliente = new javax.swing.JLabel();
        lblAvisoCodigo = new javax.swing.JLabel();
        lblAvisoCantidad = new javax.swing.JLabel();
        lblAvisoFormaPago = new javax.swing.JLabel();
        lblAvisoSubtotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setAlignmentY(0.0F);
        jPanel4.setLayout(null);

        rSLabelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSistemaFinal.jpg"))); // NOI18N
        jPanel4.add(rSLabelImage5);
        rSLabelImage5.setBounds(600, 10, 160, 70);

        btnDetalleFactura.setBackground(new java.awt.Color(0, 153, 102));
        btnDetalleFactura.setText("Detalle Factura");
        btnDetalleFactura.setBgHover(new java.awt.Color(102, 102, 102));
        btnDetalleFactura.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.NOTE);
        btnDetalleFactura.setSizeIcon(30.0F);
        btnDetalleFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleFacturaActionPerformed(evt);
            }
        });
        jPanel4.add(btnDetalleFactura);
        btnDetalleFactura.setBounds(140, 10, 140, 70);

        btnFactura.setBackground(new java.awt.Color(0, 153, 102));
        btnFactura.setText("Factura");
        btnFactura.setBgHover(new java.awt.Color(102, 102, 102));
        btnFactura.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SHOPPING_CART);
        btnFactura.setSizeIcon(30.0F);
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        jPanel4.add(btnFactura);
        btnFactura.setBounds(400, 10, 100, 70);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 50, 1160, 90);

        btnGuardar1.setBackground(new java.awt.Color(0, 204, 51));
        btnGuardar1.setText("Guardar");
        btnGuardar1.setColorHover(new java.awt.Color(102, 102, 102));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardar1);
        btnGuardar1.setBounds(440, 640, 130, 30);

        labelIcon13.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon13.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        jPanel3.add(labelIcon13);
        labelIcon13.setBounds(400, 640, 30, 30);

        btnMinimizar1.setBackground(new java.awt.Color(255, 255, 255));
        btnMinimizar1.setForeground(new java.awt.Color(102, 102, 102));
        btnMinimizar1.setBackgroundHover(new java.awt.Color(0, 102, 204));
        btnMinimizar1.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnMinimizar1.setForegroundText(new java.awt.Color(102, 102, 102));
        btnMinimizar1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REMOVE);
        btnMinimizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnMinimizar1);
        btnMinimizar1.setBounds(700, 0, 40, 40);

        btnSalir1.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir1.setForeground(new java.awt.Color(102, 102, 102));
        btnSalir1.setBackgroundHover(new java.awt.Color(255, 0, 0));
        btnSalir1.setForegroundHover(new java.awt.Color(102, 102, 102));
        btnSalir1.setForegroundText(new java.awt.Color(102, 102, 102));
        btnSalir1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalir1);
        btnSalir1.setBounds(740, 0, 40, 40);

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoSistemaFinal.jpg"))); // NOI18N
        jPanel3.add(rSLabelImage3);
        rSLabelImage3.setBounds(10, 10, 50, 40);

        rSLabelHora2.setForeground(new java.awt.Color(102, 102, 102));
        rSLabelHora2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(rSLabelHora2);
        rSLabelHora2.setBounds(540, 0, 140, 40);

        rSLabelFecha2.setForeground(new java.awt.Color(102, 102, 102));
        rSLabelFecha2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(rSLabelFecha2);
        rSLabelFecha2.setBounds(420, 0, 130, 40);

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("ELECTROCASA");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(70, 10, 190, 30);

        btnRegresar.setBackground(new java.awt.Color(0, 204, 51));
        btnRegresar.setText("Regresar");
        btnRegresar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REPLAY);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegresar);
        btnRegresar.setBounds(270, 10, 120, 30);

        txtidPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtidPersona.setForeground(new java.awt.Color(102, 102, 102));
        txtidPersona.setBorder(null);
        txtidPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtidPersonaMouseClicked(evt);
            }
        });
        txtidPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidPersonaActionPerformed(evt);
            }
        });
        jPanel3.add(txtidPersona);
        txtidPersona.setBounds(580, 180, 160, 30);

        txtnombreCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnombreCliente.setForeground(new java.awt.Color(102, 102, 102));
        txtnombreCliente.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtnombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombreClienteMouseClicked(evt);
            }
        });
        txtnombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreClienteActionPerformed(evt);
            }
        });
        jPanel3.add(txtnombreCliente);
        txtnombreCliente.setBounds(190, 250, 160, 30);

        txtCedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(102, 102, 102));
        txtCedula.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCedulaMouseClicked(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel3.add(txtCedula);
        txtCedula.setBounds(190, 210, 160, 30);

        txtCantidadProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCantidadProducto.setForeground(new java.awt.Color(102, 102, 102));
        txtCantidadProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtCantidadProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCantidadProductoMouseClicked(evt);
            }
        });
        txtCantidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadProductoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCantidadProducto);
        txtCantidadProducto.setBounds(190, 330, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Cantidad:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(40, 330, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText(" Cliente:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(40, 250, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Cédula Cliente:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 210, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Nro Factura:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(40, 170, 110, 30);

        labelIcon8.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        jPanel3.add(labelIcon8);
        labelIcon8.setBounds(390, 200, 30, 30);

        labelIcon9.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon9.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        jPanel3.add(labelIcon9);
        labelIcon9.setBounds(390, 300, 30, 30);

        btnCalcular.setBackground(new java.awt.Color(102, 153, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setColorHover(new java.awt.Color(102, 102, 102));
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel3.add(btnCalcular);
        btnCalcular.setBounds(620, 560, 110, 30);

        btnBuscarProducto1.setBackground(new java.awt.Color(204, 0, 255));
        btnBuscarProducto1.setText("Buscar");
        btnBuscarProducto1.setColorHover(new java.awt.Color(102, 102, 102));
        btnBuscarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProducto1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarProducto1);
        btnBuscarProducto1.setBounds(420, 300, 100, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Forma Pago:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(120, 580, 100, 20);

        txtFormaPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFormaPago.setForeground(new java.awt.Color(102, 102, 102));
        txtFormaPago.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtFormaPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFormaPagoMouseClicked(evt);
            }
        });
        txtFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFormaPagoActionPerformed(evt);
            }
        });
        jPanel3.add(txtFormaPago);
        txtFormaPago.setBounds(220, 580, 120, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Subtotal:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(440, 540, 70, 30);

        txtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSubtotal.setForeground(new java.awt.Color(102, 102, 102));
        txtSubtotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtSubtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSubtotalMouseClicked(evt);
            }
        });
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });
        jPanel3.add(txtSubtotal);
        txtSubtotal.setBounds(510, 540, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Iva:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(440, 570, 70, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Total:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(440, 600, 70, 30);

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(102, 102, 102));
        txtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalMouseClicked(evt);
            }
        });
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel3.add(txtTotal);
        txtTotal.setBounds(510, 600, 90, 30);

        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaFactura.setBackgoundHead(new java.awt.Color(102, 0, 102));
        jScrollPane3.setViewportView(tablaFactura);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(90, 370, 640, 170);

        rSLabelFecha1.setForeground(new java.awt.Color(102, 102, 102));
        rSLabelFecha1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.add(rSLabelFecha1);
        rSLabelFecha1.setBounds(440, 150, 120, 30);

        checkBoxIVA.setText("14%");
        checkBoxIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIVAActionPerformed(evt);
            }
        });
        jPanel3.add(checkBoxIVA);
        checkBoxIVA.setBounds(510, 580, 49, 23);

        btnBuscarCliente2.setBackground(new java.awt.Color(204, 0, 255));
        btnBuscarCliente2.setText("Buscar");
        btnBuscarCliente2.setColorHover(new java.awt.Color(102, 102, 102));
        btnBuscarCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCliente2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarCliente2);
        btnBuscarCliente2.setBounds(420, 210, 100, 20);

        txtFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFactura.setForeground(new java.awt.Color(102, 102, 102));
        txtFactura.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFacturaMouseClicked(evt);
            }
        });
        jPanel3.add(txtFactura);
        txtFactura.setBounds(190, 160, 160, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Código Producto:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(40, 290, 130, 30);

        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(102, 102, 102));
        txtCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(217, 219, 228)));
        txtCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoMouseClicked(evt);
            }
        });
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodigo);
        txtCodigo.setBounds(190, 290, 160, 30);

        btnLimpiar.setBackground(new java.awt.Color(0, 102, 51));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setColorHover(new java.awt.Color(102, 102, 102));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpiar);
        btnLimpiar.setBounds(150, 640, 130, 30);

        labelIcon14.setForeground(new java.awt.Color(102, 102, 102));
        labelIcon14.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        jPanel3.add(labelIcon14);
        labelIcon14.setBounds(110, 640, 30, 30);

        lblAvisoCedula.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCedula.setText("*");
        jPanel3.add(lblAvisoCedula);
        lblAvisoCedula.setBounds(360, 210, 20, 14);

        lblAvisoTotal.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoTotal.setText("*");
        jPanel3.add(lblAvisoTotal);
        lblAvisoTotal.setBounds(600, 610, 30, 14);

        lblAvisoFactura.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoFactura.setText("*");
        jPanel3.add(lblAvisoFactura);
        lblAvisoFactura.setBounds(360, 170, 30, 14);

        lblAvisoCliente.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCliente.setText("*");
        jPanel3.add(lblAvisoCliente);
        lblAvisoCliente.setBounds(360, 250, 30, 14);

        lblAvisoCodigo.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCodigo.setText("*");
        jPanel3.add(lblAvisoCodigo);
        lblAvisoCodigo.setBounds(360, 290, 30, 14);

        lblAvisoCantidad.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoCantidad.setText("*");
        jPanel3.add(lblAvisoCantidad);
        lblAvisoCantidad.setBounds(360, 330, 30, 14);

        lblAvisoFormaPago.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoFormaPago.setText("*");
        jPanel3.add(lblAvisoFormaPago);
        lblAvisoFormaPago.setBounds(350, 580, 30, 14);

        lblAvisoSubtotal.setForeground(new java.awt.Color(255, 0, 0));
        lblAvisoSubtotal.setText("*");
        jPanel3.add(lblAvisoSubtotal);
        lblAvisoSubtotal.setBounds(600, 550, 30, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetalleFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleFacturaActionPerformed
        dispose();
        //Vista
        DetalleFactura detalle = new DetalleFactura();
        detalle.setLocationRelativeTo(null);
        dispose();
        detalle.setVisible(true);

    }//GEN-LAST:event_btnDetalleFacturaActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnMinimizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizar1ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizar1ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtidPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidPersonaMouseClicked

    }//GEN-LAST:event_txtidPersonaMouseClicked

    private void txtnombreClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreClienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreClienteMouseClicked

    private void txtnombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreClienteActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreClienteActionPerformed

    private void txtCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaMouseClicked

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCantidadProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCantidadProductoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoMouseClicked

    private void txtCantidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //subtotal();
        if (txtSubtotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese los productos que desea vender");

        } else {
            calcularIva();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnBuscarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProducto1ActionPerformed
        if (txtCodigo.getText().equals("") || txtCantidadProducto.getText().equals("")) {
            lblAvisoCodigo.setVisible(true);
            lblAvisoCantidad.setVisible(true);
            JOptionPane.showMessageDialog(null, "Por favor, ingrese el código, cantidad del producto");
        } else {
            if (controles.validarNumeroEntero(txtCodigo.getText())) {
                if (controles.validarNumeroEntero(txtCantidadProducto.getText())) {
                    produc = fac.buscarProductoFactura(txtCodigo.getText(), Integer.valueOf(txtCantidadProducto.getText()));
                    listaProductos.add(produc);
                    calcularSubtotal();
                    txtSubtotal.setText(String.valueOf(subtotal));

                    for (Producto listaProducto : listaProductos) {
                        listaProducto.getCodigo();
                        listaProducto.getStock();
                        System.out.println("id" + listaProducto.getIdProducto());
                        System.out.println("codigo" + listaProducto.getCodigo());
                        System.out.println("cod stock" + listaProducto.getStock());
                    }
                    mostrarTabla();
                    fac.actualizarStockBD(txtCodigo.getText(), Integer.valueOf(txtCantidadProducto.getText()));

                } else {
                    JOptionPane.showMessageDialog(null, "Cantidad Incorrecto");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Código del Producto Incorrecto");
            }

        }

///////////////////////        

    }//GEN-LAST:event_btnBuscarProducto1ActionPerformed

    private void txtFormaPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFormaPagoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormaPagoMouseClicked

    private void txtFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormaPagoActionPerformed

    private void txtSubtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSubtotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalMouseClicked

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        txtSubtotal.setEnabled(false);

    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMouseClicked

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    public boolean camposVacios() {
        if (txtFactura.getText().equals("") || txtCedula.getText().equals("") || txtnombreCliente.getText().equals("")
                || txtCodigo.getText().equals("") || txtCantidadProducto.getText().equals("") || txtFormaPago.getText().equals("")
                || txtSubtotal.getText().equals("") || txtTotal.getText().equals("")) {

            lblAvisoCedula.setVisible(true);
            lblAvisoCliente.setVisible(true);
            lblAvisoCodigo.setVisible(true);
            lblAvisoCantidad.setVisible(true);
            lblAvisoFormaPago.setVisible(true);
            lblAvisoSubtotal.setVisible(true);
            lblAvisoTotal.setVisible(true);
            lblAvisoFactura.setVisible(true);
            return true;
        } else {
            return false;
        }
    }
    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        if (camposVacios()) {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar");
        } else {
            if (controles.Numero(txtFactura.getText())) {
                FacturaDAO fac1 = new FacturaDAO();
                Date fecha = new Date();
                Persona persona = new Persona();
                persona.setIdPersona(Long.valueOf(txtidPersona.getText()));
                String nroFactura = txtFactura.getText();
                Boolean iva = checkBoxIVA.isSelected();
                String formaPago = txtFormaPago.getText();
                String idAci = "";
                Boolean estado = false;
                double subtotal = Double.parseDouble(txtSubtotal.getText());
                double total = Double.parseDouble(txtTotal.getText());
                fac1.insertarFactura(fecha, formaPago, iva, nroFactura, subtotal, total, persona, idAci, estado);
                JOptionPane.showMessageDialog(rootPane, "Factura agregada");
                mostrarTabla();
                limpiar();

            } else {
                JOptionPane.showMessageDialog(null, "Numero de factura incorrecto");
            }

        }

// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        FiveCodMover.FiveCodMoverJFrame.MousePressed(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        FiveCodMover.FiveCodMoverJFrame.MouseDraggedFrame(evt, this);

        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void checkBoxIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxIVAActionPerformed

    private void btnBuscarCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCliente2ActionPerformed
        if (txtCedula.getText().equals("") || txtCedula.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese la cédula del Cliente");
            lblAvisoCedula.setVisible(true);
        } else {
            mostrarNombreCliente(txtCedula.getText());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCliente2ActionPerformed

    private void txtFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFacturaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturaMouseClicked

    private void txtidPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidPersonaActionPerformed

    private void txtCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMouseClicked

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    private void calcularIva() {
        double subtotal = Double.parseDouble(txtSubtotal.getText());
        boolean iva = checkBoxIVA.isSelected();
        double total;
        double totaliva;
        double ivaT;
        double resta;
        if (iva == true) {
            ivaT = 1.14;
            totaliva = subtotal / ivaT;
            resta = subtotal - totaliva;
            total = subtotal + resta;
            double roundDbl = Math.round(total * 100.0) / 100.0;
            txtTotal.setText(String.valueOf(roundDbl));

        } else {
            total = subtotal;
            txtTotal.setText(String.valueOf(total));
        }
    }

    public void calcularSubtotal() {
        subtotal += fac.calcularSubtotal(listaProductos, Integer.parseInt(txtCantidadProducto.getText()));

    }

    private void limpiar() {
        txtFactura.setText("");
        txtCedula.setText("");
        txtnombreCliente.setText("");
        txtCodigo.setText("");
        txtCantidadProducto.setText("");
        txtFormaPago.setText("");
        txtSubtotal.setText("");
        txtTotal.setText("");

        lblAvisoCedula.setVisible(false);
        lblAvisoCliente.setVisible(false);
        lblAvisoCodigo.setVisible(false);
        lblAvisoCantidad.setVisible(false);
        lblAvisoFormaPago.setVisible(false);
        lblAvisoSubtotal.setVisible(false);
        lblAvisoTotal.setVisible(false);
        lblAvisoFactura.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonHover btnBuscarCliente2;
    private rojerusan.RSButtonHover btnBuscarProducto1;
    private rojerusan.RSButtonHover btnCalcular;
    private newscomponents.RSButtonBigIcon_new btnDetalleFactura;
    private newscomponents.RSButtonBigIcon_new btnFactura;
    private rojerusan.RSButtonHover btnGuardar1;
    private rojerusan.RSButtonHover btnLimpiar;
    private RSMaterialComponent.RSButtonIconDos btnMinimizar1;
    private newscomponents.RSButtonIcon_new btnRegresar;
    private RSMaterialComponent.RSButtonIconDos btnSalir1;
    private javax.swing.JCheckBox checkBoxIVA;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private necesario.LabelIcon labelIcon13;
    private necesario.LabelIcon labelIcon14;
    private necesario.LabelIcon labelIcon8;
    private necesario.LabelIcon labelIcon9;
    private javax.swing.JLabel lblAvisoCantidad;
    private javax.swing.JLabel lblAvisoCedula;
    private javax.swing.JLabel lblAvisoCliente;
    private javax.swing.JLabel lblAvisoCodigo;
    private javax.swing.JLabel lblAvisoFactura;
    private javax.swing.JLabel lblAvisoFormaPago;
    private javax.swing.JLabel lblAvisoSubtotal;
    private javax.swing.JLabel lblAvisoTotal;
    private rojeru_san.rsdate.RSLabelFecha rSLabelFecha1;
    private rojeru_san.rsdate.RSLabelFecha rSLabelFecha2;
    private rojeru_san.rsdate.RSLabelHora rSLabelHora2;
    private necesario.RSLabelImage rSLabelImage3;
    private necesario.RSLabelImage rSLabelImage5;
    private RSMaterialComponent.RSTableMetro tablaFactura;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFactura;
    private javax.swing.JTextField txtFormaPago;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtidPersona;
    private javax.swing.JTextField txtnombreCliente;
    // End of variables declaration//GEN-END:variables
}
